# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

Write a Python program to manage and analyze order data stored in a CSV file. The program should:

Ask the user for the CSV filename (including the .csv extension) and load it into a Pandas DataFrame named orders.
Extract and display the TotalAmount column for all orders.
Ask the user for an order number (e.g., 4) and display the details of that order.
Calculate and display the average of all TotalAmount values.
Ask the user for an OrderID, a new PaymentMethod, and a new TotalAmount, then update the matching order record in the DataFrame accordingly and display the updated order.

Enter the CSV filename (with .csv extension):
--- Orders DataFrame Loaded ---
  order_id user_id  ... payment_method order_status
0  ORD0001  USR002  ...    Credit Card    Completed
1  ORD0002  USR065  ...            UPI    Completed
2  ORD0003  USR080  ...           Cash    Completed
3  ORD0004  USR098  ...         Wallet    Cancelled
4  ORD0005  USR147  ...         Wallet    Cancelled

[5 rows x 8 columns]

Total Amounts of All Orders:
0     2188
1      636
2     3399
3     3126
4     3123
5      380
6     2581
7     3239
8     3259
9     3088
10    3033
11    2958
12     587
13    2227
14    1201
15     381
16     559
17    2536
18    1377
19    2275
20     393
21    2304
22    1605
23     356
24    3149
25    2870
26    2502
27     646
28    1467
29    2931
30    1155
31    1492
32    1248
33    2843
34    1114
35    3135
36    3253
37    3164
38    1962
39     404
40    2738
41    2724
42     840
43    1985
44    2410
45    2378
46    2122
47    2264
48    1197
49     892
Name: total_amount, dtype: int64

Details of the 4th order:
order_id                             ORD0004
user_id                               USR098
restaurant_id                         RST013
order_date                          1/4/2024
total_amount                            3126
items_ordered     Butter Naan, Chicken Curry
payment_method                        Wallet
order_status                       Cancelled
Name: 3, dtype: object

Average Total Amount: ₹1993.92

Updated details for ORD0004:
  order_id user_id  ... payment_method order_status
3  ORD0004  USR098  ...            UPI    Cancelled

[1 rows x 8 columns]

In [23]:
from pathlib import Path

def find_csv_file_path(filename, directory='.'):
    search_path = Path(directory)
    for path in search_path.rglob(f'{filename}'):
        return str(path.resolve())
    return None

import pandas as pd
print("Enter the CSV filename (with .csv extension):")
df = pd.read_csv(find_csv_file_path("sample.csv"))
print("--- Orders DataFrame Loaded ---")
print(df.head())

print("Total Amounts of All Orders:")
print(df[['total_amount']].to_string(header=False))
print(f"Name: total_amount, dtype: {df['total_amount'].dtype}")

print("Details of the 4th order:")
print(df.iloc[3])
print(f"Average Total Amount: ₹{df['total_amount'].mean():.2f}")

print("Updated details for ORD0004:")
df.loc[3, "order_status"] = "Cancelled"
df.loc[3, "payment_method"] = "UPI"
print(df[df['order_id'] == 'ORD0004'])

Enter the CSV filename (with .csv extension):
--- Orders DataFrame Loaded ---
  order_id user_id restaurant_id order_date  total_amount  \
0  ORD0001  USR002        RST007   1/4/2024          2188
1  ORD0002  USR065        RST044   1/4/2024           636
2  ORD0003  USR080        RST058   1/4/2024          3399
3  ORD0004  USR098        RST013   1/4/2024          3126
4  ORD0005  USR147        RST030   1/4/2024          3123

                                       items_ordered payment_method  \
0             Fried Rice, Masala Dosa, Hakka Noodles    Credit Card
1  Samosa, Hakka Noodles, Paneer Butter Masala, F...            UPI
2                          Fried Rice, Hakka Noodles           Cash
3                         Butter Naan, Chicken Curry         Wallet
4           Mutton Rogan Josh, Chole Bhature, Samosa         Wallet

  order_status
0    Completed
1    Completed
2    Completed
3    Cancelled
4    Cancelled
Total Amounts of All Orders:
0   2188
1    636
2   3399
3   3126
4   3123
5    380
6   2581
7   3239
8   3259
9   3088
10  3033
11  2958
12   587
13  2227
14  1201
15   381
16   559
17  2536
18  1377
19  2275
20   393
21  2304
22  1605
23   356
24  3149
25  2870
26  2502
27   646
28  1467
29  2931
30  1155
31  1492
32  1248
33  2843
34  1114
35  3135
36  3253
37  3164
38  1962
39   404
40  2738
41  2724
42   840
43  1985
44  2410
45  2378
46  2122
47  2264
48  1197
49   892
Name: total_amount, dtype: int64
Details of the 4th order:
order_id                             ORD0004
user_id                               USR098
restaurant_id                         RST013
order_date                          1/4/2024
total_amount                            3126
items_ordered     Butter Naan, Chicken Curry
payment_method                        Wallet
order_status                       Cancelled
Name: 3, dtype: object
Average Total Amount: ₹1993.92
Updated details for ORD0004:
  order_id user_id restaurant_id order_date  total_amount  \
3  ORD0004  USR098        RST013   1/4/2024          3126

                items_ordered payment_method order_status
3  Butter Naan, Chicken Curry            UPI    Cancelled